const ORDER_STATUSES = {
    PLACED: 'PLACED',
    PACKED: 'PACKED',
    DISPATCHED: 'DISPATCHED',
    DELIVERED: 'DELIVERED',
};

const DATE_FORMAT = 'D-MM-YYYY';

module.exports = {
    ORDER_STATUSES,
    DATE_FORMAT,
};
